#!/bin/bash

# CS 3205 Assignment 1 - Question 5
# YouTube Streaming Analysis

OUTPUT_DIR="q5_outputs"
mkdir -p "$OUTPUT_DIR"

echo "======================================================"
echo "Question 5: YouTube Streaming Analysis"
echo "======================================================"
echo ""
echo "INSTRUCTIONS:"
echo "-------------"
echo ""
echo "1. Open a web browser and go to YouTube"
echo "2. In another terminal, start packet capture:"
echo ""
echo "   sudo tcpdump -i en0 -w q5_outputs/youtube_capture.pcap 'host (googlevideo.com or youtube.com)'"
echo ""
echo "   (Replace 'en0' with your active network interface if different)"
echo "   (Run 'ifconfig' to see available interfaces)"
echo ""
echo "3. Play a YouTube video for exactly 30 seconds"
echo ""
echo "4. Stop the packet capture (Ctrl+C in the tcpdump terminal)"
echo ""
echo "5. Run the analysis script:"
echo ""
echo "   python3 q5_youtube_analysis.py"
echo ""
echo "======================================================"
echo ""
echo "Network Interfaces on your system:"
ifconfig | grep -E "^[a-z]" | cut -d: -f1
echo ""
echo "Common interfaces:"
echo "  - en0: Usually Wi-Fi"
echo "  - en1: Usually Ethernet"
echo "  - utun0-3: VPN interfaces"
echo ""
echo "To find your active interface with internet:"
echo "  route get google.com | grep interface"
echo ""
